import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Platform } from 'react-native';
import { AnswerKeyItem, ClassExamAnalytics, Exam, ScanResult } from '../../types';

/**
 * Generates and exports the Official Answer Key Matrix as a printable PDF
 */
export async function generateAnswerKeyMatrixPDF(
  exam: Exam,
  answerKeys: AnswerKeyItem[]
): Promise<string | null> {
  const optionsCount = exam.options_per_question || 4;
  const optionLetters = ['A', 'B', 'C', 'D', 'E'].slice(0, optionsCount);
  const totalQuestions = exam.total_questions || 50;

  // Split into 2 equal columns for clear layout
  const mid = Math.ceil(totalQuestions / 2);
  const col1 = answerKeys.slice(0, mid);
  const col2 = answerKeys.slice(mid, totalQuestions);

  const renderColRows = (items: AnswerKeyItem[]) =>
    items
      .map((k) => {
        const bubblesHtml = optionLetters
          .map((opt) => {
            const isPicked = k.correct_options.includes(opt);
            return `<span class="bubble ${isPicked ? 'picked' : ''}">${opt}</span>`;
          })
          .join('');

        return `
        <div class="row">
          <span class="q-num">Q${k.question_number}</span>
          <div class="bubbles-row">${bubblesHtml}</div>
        </div>
      `;
      })
      .join('');

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Answer Key Matrix - ${exam.title}</title>
      <style>
        * { box-sizing: border-box; }
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; margin: 0; padding: 24px; color: #0f172a; background: #ffffff; }
        .header { text-align: center; border-bottom: 3px solid #4f46e5; padding-bottom: 12px; margin-bottom: 16px; }
        .header h1 { margin: 0; color: #4f46e5; font-size: 22px; font-weight: 800; text-transform: uppercase; letter-spacing: 0.5px; }
        .header h3 { margin: 4px 0 0 0; color: #64748b; font-size: 14px; font-weight: 600; }
        
        .meta-card { display: flex; justify-content: space-between; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 10px; padding: 12px 18px; margin-bottom: 20px; font-size: 12px; }
        .meta-card div { color: #475569; }
        .meta-card strong { color: #0f172a; }

        .matrix-container { display: flex; gap: 20px; }
        .matrix-column { flex: 1; border: 1px solid #cbd5e1; border-radius: 8px; overflow: hidden; }
        .col-header { background: #4f46e5; color: #ffffff; font-size: 11px; font-weight: 700; padding: 6px 12px; text-transform: uppercase; }

        .row { display: flex; align-items: center; justify-content: space-between; padding: 5px 12px; border-bottom: 1px solid #f1f5f9; font-size: 12px; }
        .row:nth-child(even) { background: #f8fafc; }
        .q-num { font-weight: 700; color: #1e293b; width: 36px; }
        .bubbles-row { display: flex; gap: 6px; }
        .bubble { width: 22px; height: 22px; border-radius: 50%; border: 1.5px solid #94a3b8; display: inline-flex; align-items: center; justify-content: center; font-size: 10px; font-weight: 700; color: #64748b; background: #ffffff; }
        .bubble.picked { background: #4f46e5; border-color: #4f46e5; color: #ffffff; }

        .footer { margin-top: 24px; text-align: center; font-size: 10px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 10px; }
        .print-toolbar { display: none; }
        @media screen {
          .print-toolbar { display: flex; justify-content: center; margin-bottom: 16px; }
          .print-toolbar button { border: 0; border-radius: 6px; background: #4f46e5; color: #ffffff; padding: 10px 18px; font-size: 14px; font-weight: 700; cursor: pointer; }
        }
        @media print { .print-toolbar { display: none !important; } }
      </style>
    </head>
    <body>
      <div class="print-toolbar"><button type="button" onclick="window.print()">Save / Print Key PDF</button></div>
      <div class="header">
        <h1>Official Answer Key Matrix</h1>
        <h3>${exam.title}</h3>
      </div>

      <div class="meta-card">
        <div><strong>Course/Section:</strong> ${exam.class_name || exam.description || 'Physics 101'}</div>
        <div><strong>Total Questions:</strong> ${totalQuestions}</div>
        <div><strong>Passing Score:</strong> ${exam.passing_score}%</div>
        <div><strong>Date:</strong> ${new Date().toLocaleDateString()}</div>
      </div>

      <div class="matrix-container">
        <div class="matrix-column">
          <div class="col-header">Questions 1 – ${mid}</div>
          ${renderColRows(col1)}
        </div>
        <div class="matrix-column">
          <div class="col-header">Questions ${mid + 1} – ${totalQuestions}</div>
          ${renderColRows(col2)}
        </div>
      </div>

      <div class="footer">
        Generated by CheckMate OMR Automated Grading System • ${exam.title}
      </div>
    </body>
    </html>
  `;

  try {
    if (Platform.OS === 'web' && typeof window !== 'undefined') {
      const printWindow = window.open('', '_blank');
      if (!printWindow) {
        throw new Error('The browser blocked the answer-key window. Allow pop-ups for localhost, then try again.');
      }
      printWindow.document.write(htmlContent);
      printWindow.document.close();
      setTimeout(() => {
        printWindow.focus();
        printWindow.print();
      }, 350);
      return 'web-printed';
    }

    const { uri } = await Print.printToFileAsync({ html: htmlContent });
    await Sharing.shareAsync(uri);
    return uri;
  } catch (error) {
    console.error('Answer Key Matrix PDF Error:', error);
    return null;
  }
}

/**
 * Generates an HTML standard OMR Answer Sheet printable PDF template with
 * 4 fiducial anchor targets and un-answered bubble matrix based on exam total questions.
 */
export async function generatePrintableAnswerSheetPDF(exam: Exam): Promise<string | null> {
  const totalQuestions = exam.total_questions || 50;
  const optionsCount = exam.options_per_question || 4;
  const optionLetters = ['A', 'B', 'C', 'D', 'E'].slice(0, optionsCount);

  // Calculate grid layout (2 columns for <= 50, 4 columns for > 50)
  const numColumns = totalQuestions > 50 ? 4 : 2;
  const perCol = Math.ceil(totalQuestions / numColumns);

  const columnsHtml = Array.from({ length: numColumns })
    .map((_, colIdx) => {
      const startQ = colIdx * perCol + 1;
      const endQ = Math.min((colIdx + 1) * perCol, totalQuestions);

      const rowsHtml = Array.from({ length: endQ - startQ + 1 })
        .map((_, rowIdx) => {
          const qNum = startQ + rowIdx;
          const bubblesHtml = optionLetters
            .map((opt) => `<span class="bubble">${opt}</span>`)
            .join('');

          return `
          <div class="item-row">
            <span class="q-num">${qNum}.</span>
            <div class="bubbles">${bubblesHtml}</div>
          </div>
        `;
        })
        .join('');

      return `<div class="column">${rowsHtml}</div>`;
    })
    .join('');

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>${exam.title} - Printable Blank Answer Sheet</title>
      <style>
        * { box-sizing: border-box; }
        @page { size: A4 portrait; margin: 15mm; }
        body { font-family: 'Helvetica Neue', Arial, sans-serif; padding: 25px; color: #0f172a; position: relative; background: #ffffff; }

        /* 4 Fiducial Anchor Markers for OMR Camera Scanner Alignment */
        .fiducial { position: absolute; width: 22px; height: 22px; border: 4px solid #000000; border-radius: 50%; background: #000000; }
        .tl { top: 10px; left: 10px; }
        .tr { top: 10px; right: 10px; }
        .bl { bottom: 10px; left: 10px; }
        .br { bottom: 10px; right: 10px; }

        .header { text-align: center; border-bottom: 2.5px solid #0f172a; padding-bottom: 8px; margin-bottom: 15px; }
        .header h1 { margin: 0; font-size: 20px; font-weight: 800; text-transform: uppercase; letter-spacing: 1px; color: #0f172a; }
        .header h3 { margin: 3px 0 0 0; color: #475569; font-size: 13px; font-weight: 600; }

        .instructions { font-size: 10px; color: #64748b; text-align: center; margin-bottom: 12px; font-style: italic; }

        .meta-table { width: 100%; border-collapse: collapse; margin-bottom: 16px; font-size: 11px; }
        .meta-table td { padding: 8px 10px; border: 1px solid #cbd5e1; }
        .meta-table strong { color: #1e293b; }

        .grid-container { display: flex; gap: 15px; justify-content: space-between; }
        .column { flex: 1; border: 1px solid #e2e8f0; border-radius: 6px; padding: 8px; }
        
        .item-row { display: flex; align-items: center; justify-content: space-between; margin-bottom: 5px; font-size: 11px; padding: 2px 4px; border-bottom: 1px solid #f1f5f9; }
        .q-num { font-weight: 700; color: #334155; width: 28px; }
        .bubbles { display: flex; gap: 6px; }
        .bubble { width: 18px; height: 18px; border: 1.5px solid #0f172a; border-radius: 50%; display: inline-flex; align-items: center; justify-content: center; font-size: 9px; font-weight: 700; color: #0f172a; background: #ffffff; }

        .footer { margin-top: 20px; text-align: center; font-size: 9px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 8px; }
      </style>
    </head>
    <body>
      <!-- 4 Corner Alignment Targets for OMR Camera Warp Matrix -->
      <div class="fiducial tl"></div>
      <div class="fiducial tr"></div>
      <div class="fiducial bl"></div>
      <div class="fiducial br"></div>

      <div class="header">
        <h1>CHECKMATE OMR STUDENT ANSWER SHEET</h1>
        <h3>${exam.title} (${totalQuestions} Questions)</h3>
      </div>

      <div class="instructions">
        ✏️ Instructions: Fill in the circles completely using a dark pencil or black pen. Do not make stray marks.
      </div>

      <table class="meta-table">
        <tr>
          <td width="55%"><strong>Student Full Name:</strong> ________________________________</td>
          <td width="45%"><strong>Student ID #:</strong> ____________________</td>
        </tr>
        <tr>
          <td><strong>Subject / Section:</strong> ${exam.class_name || exam.description || 'Physics 101'}</td>
          <td><strong>Date:</strong> ____________________</td>
        </tr>
      </table>

      <div class="grid-container">
        ${columnsHtml}
      </div>

      <div class="footer">
        CheckMate OMR Sheet • ${exam.title} • Keep sheet flat and un-creased for automated camera scanning.
      </div>
    </body>
    </html>
  `;

  try {
    if (Platform.OS === 'web' && typeof window !== 'undefined') {
      const printWindow = window.open('', '_blank');
      if (printWindow) {
        printWindow.document.write(htmlContent);
        printWindow.document.close();
        printWindow.focus();
        setTimeout(() => {
          printWindow.print();
        }, 250);
        return 'web-printed';
      }
    }

    const { uri } = await Print.printToFileAsync({ html: htmlContent });
    await Sharing.shareAsync(uri);
    return uri;
  } catch (error) {
    console.error('Printable Answer Sheet PDF Error:', error);
    return null;
  }
}


/**
 * Generates class summary report PDF
 */
export async function generateClassReportPDF(
  exam: Exam,
  analytics: ClassExamAnalytics,
  scans: ScanResult[]
): Promise<string | null> {
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Class Report - ${exam.title}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 25px; color: #0f172a; }
        .title { font-size: 22px; font-weight: bold; color: #4f46e5; margin-bottom: 5px; }
        .subtitle { font-size: 14px; color: #64748b; margin-bottom: 20px; }
        .card-grid { display: flex; gap: 15px; margin-bottom: 25px; }
        .card { flex: 1; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 12px; text-align: center; }
        .card-val { font-size: 20px; font-weight: bold; color: #0f172a; }
        .card-lbl { font-size: 11px; color: #64748b; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; font-size: 12px; }
        th, td { border: 1px solid #cbd5e1; padding: 8px; text-align: left; }
        th { background: #f1f5f9; }
      </style>
    </head>
    <body>
      <div class="title">CheckMate Class Analytics Report</div>
      <div class="subtitle">Exam: ${exam.title} | Scanned Sheets: ${analytics.total_scans}</div>

      <div class="card-grid">
        <div class="card"><div class="card-val">${analytics.mean_score}</div><div class="card-lbl">Mean Score</div></div>
        <div class="card"><div class="card-val">${analytics.passing_rate}%</div><div class="card-lbl">Passing Rate</div></div>
        <div class="card"><div class="card-val">${analytics.kr20_reliability}</div><div class="card-lbl">KR-20 Reliability</div></div>
        <div class="card"><div class="card-val">${analytics.highest_score} / ${analytics.lowest_score}</div><div class="card-lbl">High / Low Score</div></div>
      </div>

      <h3>Student Score Summary</h3>
      <table>
        <thead>
          <tr>
            <th>Student Number</th>
            <th>Name</th>
            <th>Raw Score</th>
            <th>Percentage</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          ${scans
            .map(
              (s) => `
            <tr>
              <td>${s.student?.student_number || 'N/A'}</td>
              <td>${s.student ? `${s.student.last_name}, ${s.student.first_name}` : 'Unassigned'}</td>
              <td>${s.raw_score} / ${s.max_score}</td>
              <td>${s.percentage_score}%</td>
              <td>${s.percentage_score >= exam.passing_score ? 'PASSED' : 'FAILED'}</td>
            </tr>
          `
            )
            .join('')}
        </tbody>
      </table>
    </body>
    </html>
  `;

  try {
    if (Platform.OS === 'web' && typeof window !== 'undefined') {
      const printWindow = window.open('', '_blank');
      if (printWindow) {
        printWindow.document.write(htmlContent);
        printWindow.document.close();
        printWindow.focus();
        setTimeout(() => {
          printWindow.print();
        }, 250);
        return 'web-printed';
      }
    }

    const { uri } = await Print.printToFileAsync({ html: htmlContent });
    await Sharing.shareAsync(uri);
    return uri;
  } catch (error) {
    console.error('Class Report Error:', error);
    return null;
  }
}
